# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "keigo-camp-test-app"
client_id = "d688457d0d8906a17b6b5a0431ff4ab3"
application_url = "https://manchester-medicine-implementation-involved.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_orders,write_orders,read_assigned_fulfillment_orders,write_assigned_fulfillment_orders,read_merchant_managed_fulfillment_orders,read_third_party_fulfillment_orders,write_merchant_managed_fulfillment_orders,write_third_party_fulfillment_orders"

[auth]
redirect_urls = [
  "https://manchester-medicine-implementation-involved.trycloudflare.com/auth/callback",
  "https://manchester-medicine-implementation-involved.trycloudflare.com/auth/shopify/callback",
  "https://manchester-medicine-implementation-involved.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "keigo-test-camp.myshopify.com"
