# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "keigo-camp-test-local"
client_id = "54d7093aa600bcecdd665045412b5f37"
application_url = "https://shopper-tracy-throughout-happen.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_orders,write_orders,read_assigned_fulfillment_orders,write_assigned_fulfillment_orders,read_merchant_managed_fulfillment_orders,read_third_party_fulfillment_orders,write_merchant_managed_fulfillment_orders,write_third_party_fulfillment_orders"

[auth]
redirect_urls = [
  "https://shopper-tracy-throughout-happen.trycloudflare.com/auth/callback",
  "https://shopper-tracy-throughout-happen.trycloudflare.com/auth/shopify/callback",
  "https://shopper-tracy-throughout-happen.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[app_proxy]
url = "https://cindy-dust-adverse-catalogue.trycloudflare.com/proxy"
subpath = "proxy"
prefix = "apps"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "keigo-test-camp.myshopify.com"
